#  Editing
#-----------------------------------------------
[[plugins]] # a simple, easy-to-use Vim alignment plugin
repo   = 'junegunn/vim-easy-align'
on_cmd = ['EasyAlign']

[[plugins]] # emmet for vim: HTML and CSS hi-speed coding
repo    = 'mattn/emmet-vim'
on_i    = 1
on_func = ['emmet']

[[plugins]]
repo = 'tpope/vim-surround'
on_i = 1

[[plugins]]
repo = 'kana/vim-operator-replace'
depends = ['vim-operator-user']
on_map = ['<Plug>(operator-replace)']

[[plugins]]
repo = 'tyru/operator-camelize.vim'
depends = ['vim-operator-user']
on_map = [
  '<Plug>(operator-camelize)',
  '<Plug>(operator-decamelize)',
  '<Plug>(operator-camelize-toggle)',
]

[[plugins]]
repo = 't9md/vim-textmanip'
on_map = ['<Plug>(textmanip-']

[[plugins]]
repo = 'Valloric/MatchTagAlways'


[[plugins]]
repo = 'AndrewRadev/splitjoin.vim'
on_i = 1

# [[plugins]]
# repo = 'vim-syntastic/syntastic'
# on_i = 1

#  Completion
#-----------------------------------------------
# [[plugins]] # accurately completing C and C++ code
# repo  = 'Rip-Rip/clang_complete'
# on_ft = ['clang', 'objc']

[[plugins]] # next generation of auto completion framework
repo = 'Shougo/neocomplete'
on_i = 1

[[plugins]] # adds snippet support
repo      = 'Shougo/neosnippet'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_i = 1

#  Utils
#-----------------------------------------------
[[plugins]] # a tree explorer
repo = 'scrooloose/nerdtree'

# Linter
#-----------------------------------------------
[[plugins]]
repo = 'tell-k/vim-autopep8'
on_ft = ['python']

[[plugins]]
repo = 'nvie/vim-flake8'
on_ft = ['python']

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = ['python']


#  Language
#-----------------------------------------------
[[plugins]] # syntax highlight for Haml
repo  = 'tpope/vim-haml'
on_ft = ['haml']

[[plugins]] # syntax highlight for Markdown
repo  = 'tpope/vim-markdown'
on_ft = ['markdown']

[[plugins]] # syntax highlight for CoffeeScript
repo  = 'kchmck/vim-coffee-script'
on_ft = ['coffee']

[[plugins]] # syntax highlight for Ruby
repo  = 'vim-ruby/vim-ruby'
on_ft = ['ruby']

[[plugins]] # working with Ruby on Rails applications
repo  = 'tpope/vim-rails'
on_ft = ['ruby']

[[plugins]] # syntax highlight for SCSS
repo  = 'cakebaker/scss-syntax.vim'
on_ft = ['scss']

[[plugins]] # syntax highlight for Scala
repo  = 'derekwyatt/vim-scala'
on_ft = ['scala']

[[plugins]] # syntax highlight for Haskell
repo  = 'kana/vim-filetype-haskell'
on_ft = ['haskell']

[[plugins]] # Elixir support for vim
repo  = 'elixir-lang/vim-elixir'
on_ft = ['elixir']

# [[plugins]]
# repo = 'othree/yajs.vim'
# on_ft = ['javascript']

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = ['javascript']

[[plugins]]
repo = 'fleischie/vim-styled-components'
on_ft = ['javascript']

[[plugins]] # python support for vim
repo = 'davidhalter/jedi-vim'
on_ft = ['python']

[[plugins]]
repo = 'lambdalisue/vim-django-support'
on_ft = ['python']

[[plugins]]
repo = 'JulesWang/css.vim'
on_ft = ['css']

[[plugins]]
repo = 'cakebaker/scss-syntax.vim'
on_ft = ['scss']

[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']

[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = ['scala']
