set transparency=10
" fonts
set guifont=Monaco:h9

" maximize window
set lines=999 columns=9999

" reset guioption
set guioptions&

" use cui
set guioptions+=c

" hide menu & toolbars
set guioptions-=T
set guioptions-=m

" disable gui tabline
set guioptions-=e

" make tabs more readable
set guitablabel=%N\ %t%M

" new window menu
menu File.New\ Window <Nop>
macm File.New\ Window action=newWindow: key=<D-n>

" send print jobs to Preview.app
set printexpr=system('open\ -a\ Preview\ '.v:fname_in)\ +\ v:shell_error
