## 3shake.zsh
# 3shake.zsh is customizing cd to 3shake's repo

## excluding go repositories
GITHUB="$HOME/w/github.com"
SHAKE="$GITHUB/3-shake"
alias shake="$SHAKE"
alias sf="$SHAKE/reckoner-frontend"
alias cdpfront="$SHAKE/reckoner-cdp-frontend"
alias sft="$SHAKE/reckoner-tmp-frontend"
alias sad="$SHAKE/reckoner-admin-frontend"
alias sadf="$SHAKE/reckoner-adn-admin-frontend"
alias sadfr="$SHAKE/reckoner-adn-admin-frontend-review"
alias slog="$SHAKE/reckoner-loginsight-aggr"
alias sfmg="$SHAKE/reckoner-fmg"
alias sag="$SHAKE/reckoner-aggregator"
alias sjs="$SHAKE/reckoner-js-sdk"
alias sios="$SHAKE/reckoner-ios-sdk"
alias sissue="$SHAKE/reckoner-issue"
alias ssbt="$SHAKE/sbt"
alias slam="$SHAKE/reckoner-lambda"
alias sim="$SHAKE/docker-base-images"
alias sin="$SHAKE/reckoner-infra"
alias sinld="$SHAKE/reckoner-infra/local/docker"
alias sadin="$SHAKE/reckoner-adn-infra"
alias sadinld="$SHAKE/reckoner-adn-infra/docker/local"
alias sdoc="$SHAKE/reckoner-document"
alias sorc="$SHAKE/reckoner-orc"

## Go Respositories
#---------------------------------
GOPUS3SHAKE="$HOME/gopus/src/github.com/3-shake"
alias gshake="$GOPUS3SHAKE"
alias scol="$GOPUS3SHAKE/reckoner-collector"
alias sdmp="$GOPUS3SHAKE/reckoner-dmp-api"
alias sweb="$GOPUS3SHAKE/reckoner-web-api"
alias spresto="$GOPUS3SHAKE/reckoner-presto"
alias swor="$GOPUS3SHAKE/reckoner-worker"
alias sudm="$GOPUS3SHAKE/reckoner-udm"
alias sadapi="$GOPUS3SHAKE/reckoner-adn-admin-api"
alias sadserver="$GOPUS3SHAKE/reckoner-adn-server"
alias sadbatch="$GOPUS3SHAKE/reckoner-adn-batch"
alias hivego="$GOPUS3SHAKE/hive-go"
alias cdp="$GOPUS3SHAKE/reckoner-cdp"
alias cdpserver="$GOPUS3SHAKE/reckoner-cdp/server"
alias cdpbatch="$GOPUS3SHAKE/reckoner-cdp/batch"
alias cdpio="$GOPUS3SHAKE/reckoner-cdp/io"
alias cdpin="$GOPUS3SHAKE/reckoner-cdp/infra"
alias cdptracking="$GOPUS3SHAKE/reckoner-cdp/tracking"
alias cdpink="$GOPUS3SHAKE/reckoner-cdp/infra/k8s"
alias cdpindoc="$GOPUS3SHAKE/reckoner-cdp/infra/docker/compose"
